version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: prisma-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    command: ["mongod", "--auth"]
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
